# Basic
title: Perry's
subtitle: Blog
description: Welcome to my blog
# 头像里面的标题
avatarTitle: Perry
# 头像里面的描述
avatarDesc: Crazy coding
url: "perryblog.com"

# Comment
comment:
    disqus: Perry
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    github: spfscmz
    # twitter: 
    mail: spfscmz@gmail.com




#
#
#  _post/ 下的文章更换成你自己的文章
#  Star me! ： https://github.com/spfscmz/perryblog
#
#


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Blog page

# Navigation buttons in the front page.s
nav:
    - {title: Archive, description: archive, url: '/archive'}   
    - {title: Tags, description: tags, url: '/tags'}      
    - {title: About, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


